/*************************************************************************
 *
 *
 * File: output.h
 *
 * Author:  Prashant Kotak
 *
 * Created: 18/08/97
 *
 * Purpose:
 *
 * History:
 *
 *************************************************************************/

#ifndef OUTPUT_H
#define OUTPUT_H

#include <string.h>

#define MSG_DEFAULT  0
#define MSG_NOSTACK  1
#define MSG_STARTING 2
#define MSG_STOPPED  3
#define MSG_READY 4
#define MSG_SOCKFAIL 5
#define MSG_BINDFAIL 6
#define MSG_LSTNFAIL 7

//void OutputMessage ( int ) ;
//void LogMessage ( int, char *, ... ) ;

#endif

