''' * Modification Log
''' 
'''****************************************************************************
'''* 1.1    Archana Chandramathi    Jan 2013    
''' <Summary>
''' MCF changes - Defined Primary, Secondary and Active IP addresses
''' </Summary>
'''****************************************************************************
Public Class ConfigKey

    'Constants for BTC Configuration
    Public Const APP_VERSION = "AppVersion"
    Public Const APP_ID = "AppID"
    Public Const CONN_STRING = "ConnString"
    Public Const DEVICE_TYPE = "DeviceType"
    Public Const IPPORT_TESTLAB = "IPPortTESTLAB"
    Public Const IPPORT = "IPPort"
    Public Const STORE_NO = "StoreNo"
    Public Const IPPORT_TFTP = "IPPort_TFTP"
    Public Const TRANSACTION_TIMEOUT = "transactionTimeout"
    Public Const DO_AUTO_RECONNECT = "DoAutoReconnect"
    Public Const CONN_TIMEOUT = "ConnTimeOut"
    Public Const TOTAL_RECONN_RETRIES = "TotalReConnRetries"
    Public Const CONN_RETRY_DELAY = "ConnRetryDelay"
    Public Const TEST_IPPORT = "TestIPPort"
    Public Const PING_TIMEOUT = "PingTimeOut"
    Public Const DEALMSG_00 = "DealMsg_00"
    Public Const DEALMSG_01 = "DealMsg_01"
    Public Const DEALMSG_02 = "DealMsg_02"
    Public Const DEALMSG_03 = "DealMsg_03"
    Public Const DEALMSG_04 = "DealMsg_04"
    Public Const DEALMSG_05 = "DealMsg_05"
    Public Const DEALMSG_06 = "DealMsg_06"
    Public Const DEALMSG_07 = "DealMsg_07"
    Public Const DEALMSG_08 = "DealMsg_08"
    Public Const DEALMSG_09 = "DealMsg_09"
    Public Const DEALMSG_10 = "DealMsg_10"
    Public Const DEALMSG_11 = "DealMsg_11"
    Public Const DEALMSG_12 = "DealMsg_12"
    Public Const DEALMSG_16 = "DealMsg_16"
    Public Const DEALMSG_31 = "DealMsg_31"
    Public Const LOG_LEVEL = "LogLevel"
    Public Const VALID_CURRENCY = "ValidCurrency"
    Public Const PREVIOUS_USER = "PreviousUser"
    Public Const DEFAULT_LAST_PC_DATE = "DefaultLastPCDate"
    Public Const AUTO_LOGOFF_TIMEOUT = "AutoLogOffTimeOut"
    Public Const USER_IDLE_TIMEOUT = "UserIdleTimeOut"
    Public Const LAST_ACTBUILD_TIME = "LastActBuildTime"
    Public Const LAST_EXDATA_DOWNLOAD_TIME = "LastExDataDownloadTime"
    Public Const ACTIVE_DATA_AVAILABILITY = "ActiveDataAvailable"
    Public Const SYNCTRL_DOWNLOAD_RETRY = "DownloadRetry"
    Public Const MESSAGE_FILE_PATH = "MessageFilePath"
    Public Const LOG_FILE_PATH = "LogFilePath"
    Public Const EXPORT_FILE_PATH = "ExportFilePath"
    Public Const DATABASE_PATH = "DataBasePath"
    Public Const TEMP_EXPORT_FILE_PATH = "TempExportFilePath"
    Public Const ACTIVE_FILE_PATH = "ActiveFilePath"
    Public Const APPLICATION_LAUNCHER = "ApplicationLauncher"
    Public Const APPLICATION_PARAMETERS = "ApplicationParameters"
    Public Const REMOTE_PATH = "RemotePath"
    Public Const ACTIVEDATA_VALID_TIME = "ActiveDataValidTime"
    Public Const CURRENCY_KEY = "ValidCurrency"
    Public Const CONTROL_FILE_NAME = "ControlFileName"
    Public Const FILENAME_FIELD_START_INDEX = "FileNameFieldStartIndex"
    Public Const FILENAME_FIELD_LENGTH = "FileNameFieldLength"
    Public Const BUILDSTATUS_FIELD_START_INDEX = "BuildStatusStartIndex"
    Public Const BUILDSTATUS_FIELD_LENGTH = "BuildStausLength"
    Public Const ACK_1 = "Acknowledgement1"
    Public Const ACK_2 = "Acknowledgement2"
    Public Const LOCAL_PATH = "LocalPath"
    Public Const TIME_LAST_BUILD_STARTINDEX = "TimeLastBuildStartIndex"
    Public Const TIME_LAST_BUILD_LENGTH = "TimeLastBuildLength"
    Public Const IS_TYPE_STARTINDEX = "IsTypeStartIndex"
    Public Const IS_TYPE_LENGTH = "IsTypeLength"
    Public Const LIST_ID = "ListID"
    Public Const CREATE_LIST_ID = "CreateListID"
    Public Const LAST_DURATION_START_INDEX = "LastDurationStartIndex"
    Public Const LAST_DURATION_LENGTH = "LastDurationStartLength"
    Public Const BATTERY_SUSPEND_TIMEOUT = "BattSuspendTimeout"
    Public Const IS_TESTING = "IsTesting"
    Public Const BEEP_PATH = "BeepPath"
    Public Const WAIT_TIME_BEFORE_RECONNECT = "WaitTimeBeforeReconnect"
    Public Const TIME_OUT_DURATION = "TimeOutDuration_InSeconds"
    'v1.1 MCF Changes
    Public Const PRIMARY_IPADDRESS = "primaryIP"
    Public Const SECONDARY_IPADDRESS = "secondaryIP"
    Public Const ACTIVE_IPADDRESS = "activeIP"
End Class

