%INCLUDE PSBF20G.J86
%INCLUDE DEALDEC.J86
%INCLUDE DEALEXT.J86
%INCLUDE PSBF20E.J86

ON ERROR GOTO ERROR.DETECTED
GOSUB MAIN.PROCESS

STOP

MAIN.PROCESS:

CALL DEAL.SET

DEAL.SESS.NUM% = 4
 CURRENT.FILE% = DEAL.SESS.NUM%
   IF END # DEAL.SESS.NUM% THEN ERROR.DETECTED
   OPEN DEAL.FILE.NAME$ KEYED RECL DEAL.RECL% AS DEAL.SESS.NUM% NODEL

INPUT "ENTER THE DEAL NUMBER " ; CMD$

WHILE I < 10  
DEAL.DEAL.NUM$ = PACK$(CMD$)
   RC% = REMOVE.DEAL(DEAL.DEAL.NUM$)
   
   print rc%
   
 I = I + 1

PRINT I

WEND 
 RETurn
 
ERROR.DETECTED:

PRINT " AN ERROR OCCURRED"

END   