Public Class ConfigKey

    'Constants for BTC Configuration
    Public Const APP_VERSION = "AppVersion"
    Public Const CONN_STRING = "ConnString"
    Public Const DEVICE_TYPE = "DeviceType"
    Public Const IPPORT_TESTLAB = "IPPortTESTLAB"
    Public Const IPPORT = "IPPort"
    Public Const PRIMARY_IPADDRESS = "primaryIP"
    Public Const SERVER_IPADDRESS_LAPTOP = "serverIPAddressLAPTOP"
    Public Const SERVER_IPADDRESS_HOME = "serverIPAddressHOME"
    Public Const SERVER_IPADDRESS_TESTLABSINGLE = "serverIPAddressTestLabSingle"
    Public Const SERVER_IPADDRESS_TESTLABCF = "serverIPAddressTestLabCF"
    Public Const STORE_NO = "StoreNo"
    Public Const IPPORT_LOCAL = "IPPortLOCAL"
    Public Const TRANSACTION_TIMEOUT = "transactionTimeout"
    Public Const DO_AUTO_RECONNECT = "DoAutoReconnect"
    Public Const CONN_TIMEOUT = "ConnTimeOut"
    Public Const TOTAL_RECONN_RETRIES = "TotalReConnRetries"
    Public Const CONN_RETRY_DELAY = "ConnRetryDelay"
    Public Const TEST_IPPORT = "TestIPPort"
    Public Const PING_TIMEOUT = "PingTimeOut"
    Public Const LOG_LEVEL = "LogLevel"
    Public Const AUTO_LOGOFF_TIMEOUT = "AutoLogOffTimeOut"
    Public Const LAST_ACTBUILD_TIME = "LastActBuildTime"
    Public Const EXPORT_FILE_PATH = "ExportFilePath"
    Public Const TEMP_EXPORT_FILE_PATH = "TempExportFilePath"
    Public Const ACTIVE_FILE_PATH = "ActiveFilePath"
    Public Const APPLICATION_LAUNCHER = "ApplicationLauncher"
    Public Const APPLICATION_PARAMETERS = "ApplicationParameters"
    Public Const REMOTE_PATH = "RemotePath"
    Public Const ACTIVEDATA_VALID_TIME = "ActiveDataValidTime"
    Public Const CURRENCY_KEY = "ValidCurrency"
    Public Const CONTROL_FILE_NAME = "ControlFileName"
    Public Const FILENAME_FIELD_START_INDEX = "FileNameFieldStartIndex"
    Public Const FILENAME_FIELD_LENGTH = "FileNameFieldLength"
    Public Const BUILDSTATUS_FIELD_START_INDEX = "BuildStatusStartIndex"
    Public Const BUILDSTATUS_FIELD_LENGTH = "BuildStausLength"
    Public Const ACK_1 = "Acknowledgement1"
    Public Const ACK_2 = "Acknowledgement2"
    Public Const LOCAL_PATH = "LocalPath"
    Public Const TIME_LAST_BUILD_STARTINDEX = "TimeLastBuildStartIndex"
    Public Const TIME_LAST_BUILD_LENGTH = "TimeLastBuildLength"
    Public Const IS_TYPE_STARTINDEX = "IsTypeStartIndex"
    Public Const IS_TYPE_LENGTH = "IsTypeLength"
    Public Const LIST_ID = "ListID"
    Public Const LAST_DURATION_START_INDEX = "LastDurationStartIndex"
    Public Const LAST_DURATION_LENGTH = "LastDurationStartLength"
    Public Const REFERENCE_FILE_DOWNLOAD_TIME = "ReferenceFileDownload"
    Public Const SECONDARY_IPADDRESS = "secondaryIP"
    Public Const ACTIVE_IPADDRESS = "activeIP"
End Class

