DEL SHOLMEC.286
DEL SHOLMEC.OBJ
DEL SHOLMFUN.OBJ
hc32 SHOLMFUN.c -retwc -debug  -def DEBUG  HIGHC B_FLEXOS
hc32 SHOLMEC.c   -retwc   -debug -def DEBUG HIGHC B_FLEXOS
link86 SHOLMEC.inp[I,S,M,NOSH,DBI]
postlink SHOLMEC.286
debugcdv SHOLMEC.286
